-- Generated by Stylix
local wezterm = require("wezterm")
wezterm.add_to_config_reload_watch_list(wezterm.config_dir)
local function stylix_wrapped_config()
    -- Pull in the wezterm API
local wezterm = require 'wezterm'

-- This table will hold the configuration.
local config = {}

-- In newer versions of wezterm, use the config_builder which will
-- help provide cleaner error messages
if wezterm.config_builder then 
  config = wezterm.config_builder()
end

enable_kitty_graphics = true

-- This is where you actually apply your configuration options
config.font_size = 8.0

--config.colors = {
--  background = '#111643'
--}

--config.window_frame = {
--  active_titlebar_bg = '#44475A',
--  inactive_titlebar_bg = '#44475A',
--}

--config.colors.tab_bar = {
--  active_tab = {
--    bg_color = '#111643',
--    fg_color = '#C0C0C0',
--  }
--}

hide_tab_bar_if_only_one_tab = true

--config.window_background_opacity = 0.80

-- and finally, return the configuration to wezterm
return config

end
local stylix_base_config = wezterm.config_builder()
local stylix_user_config = stylix_wrapped_config()
stylix_base_config = {
    -- Set due to the default fancy tabs not respecting colorschemes
    -- See https://github.com/wez/wezterm/issues/2615
    use_fancy_tab_bar = false,
    color_scheme = "tokyonight_night",
    --font = wezterm.font_with_fallback {
        --"JetBrains Mono",
        --"Noto Color Emoji",
    --},
    font_size = 12,
    window_background_opacity = 1.000000,
    window_frame = {
        active_titlebar_bg = "#444b6a",
        active_titlebar_fg = "#a9b1d6",
        active_titlebar_border_bottom = "#444b6a",
        border_left_color = "#16161e",
        border_right_color = "#16161e",
        border_bottom_color = "#16161e",
        border_top_color = "#16161e",
        button_bg = "#16161e",
        button_fg = "#a9b1d6",
        button_hover_bg = "#a9b1d6",
        button_hover_fg = "#444b6a",
        inactive_titlebar_bg = "#16161e",
        inactive_titlebar_fg = "#a9b1d6",
        inactive_titlebar_border_bottom = "#444b6a",
    },
    command_palette_bg_color = "#16161e",
    command_palette_fg_color = "#a9b1d6",
    command_palette_font_size = 10,
}
for key, value in pairs(stylix_user_config) do
    stylix_base_config[key] = value
end
return stylix_base_config
